- name: "Clone neovim release from repo"
  ansible.builtin.get_url:
    url: "https://github.com/neovim/neovim/releases/download/{{ neovim_version }}/nvim-linux64.tar.gz" #v0.10.2
    dest: "{{ tmp_dir }}"
  tags: neovim

- name: "Extract Neovim install files"
  become: true
  unarchive:
    src: "{{ tmp_dir }}/nvim-linux64.tar.gz"
    dest: "/opt/"
  tags: neovim

- name: "Clone neovim configuration"
  ansible.builtin.git:
    repo: "git@github.com:Leninner/nvim-config.git" #v0.10.2
    dest: "/home/{{ user }}/.config/nvim/"
    force: yes
    accept_hostkey: true
    update: yes
  tags: neovim

- name: "Remove Neovim archive"
  file:
    path: "{{ tmp_dir }}/nvim-linux64.tar.gz"
    state: absent
  tags: neovim
