- name: Configure mysql
  hosts: databases
  become: true
  tags:
    - databases
  roles:
    - database

- name: Configure webserver with Nginx and PHP-FPM
  hosts: webservers
  become: true
  tags:
    - webservers
  roles:
    - webserver
